name: Cloud
favicon: null
layout_spectrum: 0.8690830960404128
typography_spectrum: 0.9024848171975464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.27908004773780704
  lightness: 0.6610864880494773
  saturation: 0.8424003466498107
  rhythmicContrast: 0.21275159809738398
purpose: []
